### ISSUE TITLE
Copy from host_vector to device_vector not trivial?

### ISSUE THREAD

**Issue by szellmann** [thrust/thrust#1002]
I noticed that when copying data from a `host_vector` to a `device_vector` that [this overload](https://github.com/thrust/thrust/blob/7df7efe3542a0ab549530bc478467320467e0094/thrust/system/cuda/detail/internal/copy_cross_system.h#L126) of the copy function is invoked because `host_vector::iterator` and `device_vector::iterator` are not the same type and thus the copy operation isn't trivial. This copy function allocates temporary arrays the size of the data being copied, which obviously prohibits copying huge arrays through `device_vector`s. Is this behavior intentional / is there a workaround (currently I just use `cudaMemcpy` to move the data around)?

**Comment by griwes** [comment]
That overload is only invoked when [this condition](https://github.com/thrust/thrust/blob/7df7efe3542a0ab549530bc478467320467e0094/thrust/system/cuda/detail/internal/copy_cross_system.h) is false. If your type doesn't match this property, we can't "just" `cudaMemcpy` it around, because that'd almost certainly break invariants established by the constructors. Instead, we do the temporary array of copies dance, and while that does indeed still involves a `cudaMemcpy` along the way - since it has to somehow get the memory to the device - we actually invoke your constructors when appropriate, both to copy on the host and to copy on the device.

This is not a perfect system, but without involving managed memory we can't really do better, and we can't "just" do that either.

Now, as I said, it's not the iterator types that govern this, and rather relocatability of your type. If you believe that your type is safe to relocate, you can tell Thrust that that's the case by [proclaiming it](https://github.com/thrust/thrust/blob/7df7efe3542a0ab549530bc478467320467e0094/thrust/type_traits/is_trivially_relocatable.h#L123).

@wash do you have anything worth adding here?

**Comment by szellmann** [comment]
Oh alright, it seems I overlooked a `iterator_value<It>::type` and erroneously thought it was about the iterator rather than about the type itself, sorry for raising this.

My struct _should_ fulfil the trivially copyable and POD etc. properties, the only thing curious about it may be that it has 32 byte alignment, that it has a union inside, and that it has some member functions, but there's no user-written ctors, dtors, inheritance or anything else involved [(it's this one here)](https://github.com/szellmann/visionaray/blob/master/include/visionaray/bvh.h#L52).

I also have to admit that I'm on an older version of thrust, the one that ships with CUDA 10.0 (OSX), and yesterday I didn't notice that newer versions have a `is_trivially_relocatable ` instead of a `is_trivial_copy` in line 221, so maybe the test is now different and possibly the data would just be trivially copied with newer thrust. Anyway good to know about `THRUST_PROCLAIM_TRIVIALLY_RELOCATABLE`!

**Comment by allisonvacanti** [comment]
This appears to be resolved. Please reopen if not.
