### ISSUE TITLE
Multiple calls to async sort results in cudaStreamSynchronize

### ISSUE THREAD

**Issue by anshumang** [thrust/thrust#1185]
How can I prevent `cudaStreamSynchronize` on back to back `thrust::async::sort` calls on the same stream?

I found `cudaStreamSynchronize` in the profiler output after each `thrust::async::sort`.

By running inside the debugger, the backtrace from `cudaStreamSynchronize` shows that the destructor of `unique_eager_event` gets called after each `thrust::async::sort`.

How do I get asynchronous behavior?

**Comment by griwes** [comment]
Please show the code you're experiencing with it; let me make a guess of what's going on in your code though.

Looking at the code right now, it seems to me that you're not saving the result from the calls to sort, which will have a synchronizing behavior. Arguably this isn't ideal, but there's a comment to that effect in the place you're describing already: handling asynchronous RAII by doing host calls from the device is not feasible, which is why, when the last owner of dependencies goes out of scope, we need to wait for the work that depends on those dependencies to finish before we destroy them.

Does your code look like

```c++
thrust::async::sort(...);
thrust::async::sort(...);
thrust::async::sort(...);
```

? If that's so, turn that into something like

```c++
auto s1 = thrust::async::sort(...);
auto s2 = thrust::async::sort(...);
auto s3 = thrust::async::sort(...);
```

**Comment by anshumang** [comment]
Yes, the code looks like 

```
thrust::async::sort(...);
thrust::async::sort(...);
thrust::async::sort(...);
```

Turning into 

```
auto s1 = thrust::async::sort(...);
auto s2 = thrust::async::sort(...);
auto s3 = thrust::async::sort(...);
```

gets rid of the `cudaStreamSynchronize`

Thanks !

Can you point me to the comment which describes this?

**Comment by griwes** [comment]
https://github.com/thrust/thrust/blob/master/thrust/system/cuda/detail/future.inl#L730-L736

I'm going to close this issue, please reopen if there's any more problems in this same area.
