### ISSUE TITLE
tips for using github thrust vs cuda SDK internal thrust

### ISSUE THREAD

**Issue by nevion** [thrust/thrust#1254]
CUDA SDK's now include both thrust and cub projects, this causes alot of mixups if you want to use github / independent from SDK thrust or cub... files that shouldn't exist will get picked up, no guarantees about mixing and matching as long as it ends up compiling (luck).

What tips are there for making things work with external to SDK thrust and cub w/ NVCC?

**Comment by allisonvacanti** [comment]
Since Thrust and CUB are header only libraries, as long as `-I /path/to/github/thrust/` and `-I /path/to/github/cub` appear before any SDK includes in the nvcc invocation everything should work.

For CMake projects, this can be simplified using the new `find_package(thrust)` configs documented [here](https://github.com/thrust/thrust/blob/main/thrust/cmake/README.md).

Feel free to reopen if that doesn't work for some reason.

**Comment by nevion** [comment]
@allisonvacanti doesn't nvcc prioritize  in the "target directory", which contains cub/thrust, automatically before any -I is applied?
from nvcc --help:
--target-directory <string>                     (-target-dir)                   
        Specify the subfolder name in the targets directory where the default include
        and library paths are located. 

The target directories contain thrust and cub.  Is there a way to basically stop the standard includes like -nostdinc / -nostdinc++ so this behavior can be avoided?

Thrust also does this:
```#include <cub/util_namespace.cuh> // This includes <cub/version.cuh> in newer releases.``
This file would only be in newer cubs, not old, right?  Which means it would see files in both distributions potentially -  partially compiling and passing version screening but using unsupported library bounds?

**Comment by allisonvacanti** [comment]
> doesn't nvcc prioritize in the "target directory", which contains cub/thrust, automatically before any -I is applied?
> The target directories contain thrust and cub. Is there a way to basically stop the standard includes like -nostdinc / -nostdinc++ so this behavior can be avoided?

By default, `nvcc` will add the toolkit's include path after any `-I` includes and before any `-isystem` includes, so specifying thrust/cub with `-I` will override the toolkit's include path -- no `-nostdinc`-like option is needed. If you're seeing different behavior, that's a bug. Can you provide more information about the issue you're having, like a complete nvcc invocation?

> Thrust also does this:
> ```
> #include <cub/util_namespace.cuh> // This includes <cub/version.cuh> in newer releases.
> ```
> This file would only be in newer cubs, not old, right? 

It's a long story, but the short version is:

Mixing thrust and cub versions is not officially supported, so ideally that would just include `cub/version.cuh`. However, that wasn't always the case, and some users of thrust had very old versions of CUB in their dependency tree and needed time to update their installations. This pattern (including `util_namespace.cuh` instead of `version.cuh`) is used as a temporary workaround while those users fix their code bases to use matching thrust/cub.

But if matching versions of thrust and cub are provided with `-I`, there shouldn't be any issues. This is what Thrust/CUB do internally for building tests, etc. to make sure that we're testing the devel versions.
