### ISSUE TITLE
OpenCL support

### ISSUE THREAD

**Issue by aoighost** [thrust/thrust#376]
While CUDA is good for Nvidia cards, the fact is that only half of the userbase can use CUDA. OpenCL support would allow for Thrust to be useful for people with AMD cards, as well as embedded Android platforms which are now getting OpenCL support.

The other advantage from implementing OpenCL would be that OpenGL 4.x has interop with OpenCL, which would allow for more possibilities regarding cross platform support.

Source on Android getting OpenCL: http://www.androidcentral.com/nexus-4-and-nexus-10-found-have-opencl-drivers

**Comment by andrewcorrigan** [comment]
There is a SYCL/OpenCL-based implementation of Parallelism TS: https://github.com/KhronosGroup/SyclParallelSTL

**Comment by jaredhoberock** [comment]
​I would like to try it out, but I can't figure out how. Is there a SYCL compiler to download?

**Comment by andrewcorrigan** [comment]
Another option has appeared, that looks promising: [cuda-on-cl](https://github.com/hughperkins/cuda-on-cl)

**Comment by andrewcorrigan** [comment]
There is an open issue with initial progress enabling Thrust support: https://github.com/hughperkins/cuda-on-cl/issues/6

**Comment by hughperkins** [comment]
> @th3flyboy How would you generate OpenCL code from e.g. a C++ function object?

Haha, that question is very prescient :-) . Pondering this at the moment...

**Comment by hughperkins** [comment]
So... it turns out that just by adding a few lines of very generic code into Coriander headers, the templated triple_chevron_launcher.cpp things from thrust become standard cudalaunch commands.  By putting into Coriander headers:

```
class ArgStore_base {
public:
    ArgStore_base() {

    }
    virtual ~ArgStore_base() {
        
    }
};

template<typename T>
class ArgStore : public ArgStore_base {
public:
    ArgStore(T arg) : arg(arg) {
    }
    T arg;
};

extern std::unique_ptr< ArgStore_base > g_arg;

#ifdef __CUDACC__
template<typename T>
size_t cudaSetupArgument(T arg, int flags) {
    std::cout << "cudaSetupArgument(T arg, int flags) from hostsideopencl_funcs.h" << std::endl;
    g_arg.reset(new ArgStore<T>(arg));
    return 0;
}
template<typename Function, typename Arg1>
void then_execute(Function fn, Arg1 arg1) {
    fn<<<(32,1,1), (32,1,1), 0>>>(arg1);
}
template<typename Function, typename Arg1>
size_t cudaLaunch(Function (*fn)(Arg1 arg1)) {
    std::cout << "cudaLaunch(T fn) from hostsideopencl_funcs.h" << std::endl;
    Arg1 arg1 = dynamic_cast<ArgStore<Arg1> *>(g_arg.get())->arg;
    // then_execute<Function, 
    fn<<<(32,0,0), (32,0,0), 0>>>(arg1);
    return 0;
}
#endif // __CUDACC__
```
... then Coriander generates the following opencl code, with no further modifications, beyond those referenced in https://github.com/hughperkins/coriander/issues/6#issuecomment-307292347 . : https://gist.github.com/hughperkins/c55bb2161a30291fd438b4c4feaf1ed2

It doesnt quite run, since missing some declaratiosn for _ZN6thrust6system4cuda6detail5bulk_6detail12_GLOBAL__N_119s_on_chip_allocatorE , but doesnt seem to face any obvious challenges, as far as the whole passing-function-by-byvalue-closure bit goes.

**Comment by brycelelbach** [comment]
Sorry, but this would be difficult for me to work on.

**Comment by maddanio** [comment]
did you see this:
https://www.khronos.org/assets/uploads/developers/resources/Intro-to-OpenCL-C++-Whitepaper-May15.pdf
this should make porting thrust to opencl relatively straight forward

**Comment by maddanio** [comment]
unless there is inside interest not to support non-nvidia gpus :)

**Comment by brycelelbach** [comment]
@maddanio - right now, there is a LOT of higher priority stuff for me. Modernizing the codebase, unifying the GitHub and CUDA versions of Thrust, improving testing and continuous integration, new major features (for all backends) that we have in the pipeline, etc.

I'm not interested in committing my time to working on this right now:

* Some of things on my list above (unifying history, improving testing and continuous integration) are needed to minimize maintenance burden before we added any new backend. The existing OMP and TBB backends are not well maintained and not tested right now. We should fix that first and lay the groundwork before we add new backends.
* Some of the new features in the pipeline will substantially change and simplifying writing backends, so we should wait for those before we add new ones.
* Most of the user base today uses the CUDA backend. I'm not sure how big of a demand there is for OpenCL.

This has nothing to do with me working at NVIDIA. I just don't think it is a good investment. It's a lot of work, it will generate a lot of maintenance work (or it will bit rot and be useless), it has pre-requisities, it will have to be rewritten in the future due to planned changes, and I don't hear many people ask for it.

I'd be happy to revisit this a year or two down the road, until (at least) we have the new backend architecture that makes it easier to add new backends.

Until then, I don't even want to encourage people to work on this as a PR, because it would all need to be rewritten. That is why I closed the bug.

**Comment by busysteve** [comment]
I use Thrust when I need it and it fits, however in most areas I work in, I'm stuck with OpenMP due to the absence of CUDA cores.  If OpenCL were to be introduced into Thrust my guess is that it would allow for better performance on platforms like Raspbery Pi.

**Comment by hughperkins** [comment]
Does raspberry pi have a gpu? I doubt that thrust will run very fast on an
opencl-enabled cpu. The work group sizes, and core characteristics are very
different.

**Comment by busysteve** [comment]
Yes.  It has a little guy.  The [Broadcom Video Core IV](https://en.wikipedia.org/wiki/VideoCore#VideoCore_key_features).  And it has OpenCL support via [VC4CL](https://github.com/doe300/VC4CL).

**Comment by gnzlbg** [comment]
How would integrating OpenCL in Thrust even work? 

How would you create an OpenCL kernel from a C++ lambda? OpenCL kernels are strings of text, so the best I can come up with is that Thrust would need its own C++ compiler for this, or at least its own pre-processor to parse C++, build an AST, identify the lambdas used as kernels, generate OpenCL kernels from these, re-write the C++ code before passing it to a C++ compiler... all of it a titanic amount of work for something that is probably going to end up as something extremely brittle unless somebody puts a lot of manpower behind it.  

Also, Thrust does supports Intel TBB and OpenMP, but the difference is that these are supported by pretty much every compiler out there (modulo MSVC). There are other programming models different from OpenCL that could be supported by Thrust (e.g. SYCL, maybe HSA, ...), but AFAIK none of these is supported by both GCC and Clang (and some are not supported by neither).

**Comment by hughperkins** [comment]
That's pretty much what Coriander does.
https://www.youtube.com/watch?v=O1zAFL6JrOM

**Comment by gnzlbg** [comment]
Given that Thrust is a header-only C++ library, if that is what Coriander does, why can't Coriander compile it and in which way isn't this a bug in Coriander itself? 

---

Also, since I cannot believe the tone of some of the comments here (@maddanio ), IIUC what is being requested here is for "somebody" to turn a simple header-only standard-compliant C++ library (that works with every standard-compliant C++ compiler), into a full blown C++ to OpenCL / SPIR-V compilation framework. 

Is that seriously what you guys are requesting?

**Comment by gnzlbg** [comment]
> Have you seen the convoluted nest of templates that Thrust uses?

Yes, I have - nobody said that compiling C++ was easy, which is why as a Thrust user I would be strongly against turning Thrust into a C++ compilation framework.

**Comment by hughperkins** [comment]
I don't think that anyone is asking to turn Thrust into a C++ compilation framework; they are stating an interest in being able to run Thrust on OpenCL devices.

I'm pretty sure if I was working on Coriander I could get Thrust working in ~1-2 months. However, I'm not, since I want to write research papers, and though the walking.md thing I linked to above might not be out of the realms of writing a research paper on, Coriander in general is not. (1-2 months meaning 'in evenings and at the weekend', though for me, that's 40 hours a week :P )

Getting SYCL working, eg trisycl https://github.com/Xilinx/triSYCL , biting the bullet of non-free, and going with CodeCompute, or writing a sycl compiler from the ground up (would probably be what I would do if I was in the position of considering the SYCL option; just more fun, gives more freedom to do whatever-needs-to-be-done), is also another option.

Whether thrust issues are the appropriate place to point that out ... well, if someone was going to build eg a SYCL framework from scratch, thrust forums are pretty much the only way to communicate with such potential creators that there is interest.

**Comment by gnzlbg** [comment]
> I don't think that anyone is asking to turn Thrust into a C++ compilation framework; they are stating an interest in being able to run Thrust on OpenCL devices.

Well [comments like @maddanio](https://github.com/thrust/thrust/issues/376#issuecomment-389683380) suggested that nVidia should be working on OpenCL support for Thrust.

I asked "how could that even work" in the second comment of this issue 4 years ago, to which the answer still appears to be that "it cannot". The third comment, also from 4 years ago, mentioned SyCL. 4 years later no mainstream compiler is planning to support SyCL in the near future. 

The root of the problem is that mainstream C++ compilers (gcc, clang, msvc) do not provide an easy way of compiling single-source C++ code to host+SPIRV/OpenCL. There is nothing that Thrust can do about this, so I don't see how this could be the appropriate venue for those discussions. This discussion is not going to reach the issue trackers of any of these compilers, and even if it did, it is not going to magically get the huge amount of work required for these issues to be solved done :/

**Comment by correaa** [comment]
Is there any news here? It would be nice to have a Thrust backend that works on SYCL. We are interested in it for Intel. (Not covered by HIP Thrust.)
