### ISSUE TITLE
string objects seem not be supported in host_vector/device_vector 

### ISSUE THREAD

**Issue by fanhk** [thrust/thrust#704]
I wrote this piece of code for testing,but it crashed when push_back the 2nd string to a host_vector<string>. 
```C
int main()
{
    ifstream input_subset("subset.txt");
    thrust::host_vector < string > h_output_subset;

    string s;
    while (getline(input_subset, s)) {
        h_output_subset.push_back(s); //crashed when put the second string into it.
    }
    cout << h_output_subset.size() << endl;
    return 0;
}
```
The input data's format is below:
>TGCCACAGGTTCCACACAACGGGACTTGGTTGAAATATTGAGATCCTTGGGGGTCTGTTAATCGG
>GTTCACGGGCCTCACGCAACGGGGCCTGGCCTAGATATTGAGGCACCCAACAGCTCTTGGCCTG
>TGCCACAGGTTCCACACAACGGGACTTGGTTGAAATATTGAGATCCTTGGGGGTCTGTTAATCGA

Is that a bug? If not, how to store strings as elements in a host_vector/device_vector?

**Comment by jaredhoberock** [comment]
Thanks for the report. It looks like a bug. Here's a smaller reproducer:

```
#include <thrust/host_vector.h>
#include <istream>
#include <iostream>

int main()
{
  thrust::host_vector<std::string> h_output_subset;

  std::string s = "s";
  h_output_subset.push_back(s);
  h_output_subset.push_back(s);

  return 0;
}
```

**Comment by jaredhoberock** [comment]
The problem is that the `copy_construct_range` dispatch process is not being conservative enough when dispatching `T`'s (in this case `std::string`) copy constructor. The less conservative path dispatches a simple copy intended for types with trivial copy constructors, but we need to dispatch the `uninitialized_copy` path which correctly uses `T`'s copy constructor because `std::string` has a non-trivial copy.

Changing the implementation of [`needs_copy_construct_via_allocator`](https://github.com/thrust/thrust/blob/master/thrust/detail/allocator/copy_construct_range.inl#L59) to the following seems to fix the problem:

```
// we need to use allocator_traits<Allocator>::construct() to
// copy construct a T if either:
// 1. Allocator has a 2-argument construct() member or
// 2. T has a non-trivial copy constructor
template<typename Allocator, typename T>
  struct needs_copy_construct_via_allocator
    : integral_constant<
        bool,
        (has_member_construct2<Allocator,T,T>::value || !has_trivial_copy_constructor<T>::value)
      >
{};


// we know that std::allocator::construct's only effect is to call T's
// copy constructor, so we needn't consider or use its construct() member for copy construction
template<typename U, typename T>
  struct needs_copy_construct_via_allocator<std::allocator<U>, T>
    : integral_constant<
        bool,
        !has_trivial_copy_constructor<T>::value
      >
{};
```
