### ISSUE TITLE
Thrust and native threading (C++11 only)

### ISSUE THREAD

**Issue by busysteve** [thrust/thrust#863]
I was wondering if Thrust provides abstracted support for `std::threading` ( Say for like when a CUDA device is not there but a rather respectful CPU is).  The idea is to allow a developer to author a Thrust supported application on a native host and later, with little or no change to code, supporting a GPU.  

If this is not an available aspect of Thrust would it be of value for someone (like myself) to add it in support of the Thrust community?

**Comment by andrewcorrigan** [comment]
There are OpenMP and TBB backends already implemented, along with a serial C++ backend.  These three different backends already make it convenient to develop on the CPU, and just recompile to run on the GPU when you need to.

Regarding `std::thread` in particular, there's nothing in this repository that uses `std::thread` as far as I am aware.  I have no idea if the Thrust developers are interested in adding additional backends, but I personally think a `std::thread` backend would be pretty useful, since it would just use standard C++ to achieve parallelization, without requiring an external library (TBB) or language extension (OpenMP).

**Comment by jaredhoberock** [comment]
There is a `cpp` backend, which is currently based on C++03 facilities. In principle, the `cpp` backend could target facilities from later language standards. One problem with attempting to target `std::thread` in particular is that it is not particularly helpful on its own. It would require quite a bit of infrastructure built on top of C++11 concurrency functionality for the backend to be worthwhile. Since we already have CPU-enabled parallelism via other means, it might be most productive to let the `cpp` backend simply wait for C++17 parallel algorithms.

**Comment by brycelelbach** [comment]
We should have implementations of the C++17 parallel algorithms from major vendors in the next few months; this should cover the CPU space. It would probably be low effort to have the cpp backend target your compiler's native CPU parallel algorithms implementation (as Jared suggests, IIUC).

**Comment by jeffhammond** [comment]
@brycelelbach
Can you point me to ETA for PSTL in GCC, Clang, etc? I use Intel PSTL and GCC's hackish approximation to PSTL. I haven't seen any discussion on Clang list in a while, but perhaps I'm not on the right one.

Is Thrust going to become the official NVIDIA C++17 PSTL implementation?

**Comment by brycelelbach** [comment]
@jeffhammond,

Please forgive me; I saw your comment a few weeks ago, meant to reply, and forgot.

> ETA for PSTL in GCC, Clang, etc?

I anticipate Visual Studio will be the first of the major three C++ compiler/standard library implementations to release a feature complete parallel algorithms library. Billy O'neal has been spending a lot of time working on it ([he and I have had some interesting discussions about implementation details on twitter](https://twitter.com/malwareminigun?lang=en)).

GCC, Clang - at least a couple of months out, I think. They both have seasoned standard library maintainers working on it.

I wouldn't be surprised if libstdc++ has it first, and libc++ ends up being the last standard library with an implementation. It's just a matter of manpower - libc++ needs more people working on it.

> Intel PSTL

I've actually haven't played around with this one yet.

> Is Thrust going to become the official NVIDIA C++17 PSTL implementation?

We're still in the process of formulating future plans for Thrust.

**Comment by jeffhammond** [comment]
@brycelelbach 

Thanks for the update.  I don't use Windows so anything in MSVC isn't useful to me, but it is good to hear that libstdc++ and libc++ are working on it.  https://gcc.gnu.org/onlinedocs/libstdc++/manual/parallel_mode_using.html seems like it's close enough that GCC will have this soon enough if people put in the effort.

Since my first post, Intel released its PSTL implementation (https://github.com/intel/parallelstl) and I have tested it in conjunction with Intel, GCC, and Clang via the PRK (e.g. https://travis-ci.org/ParRes/Kernels/builds/287622978).  This looks like an existence proof that PSTL can be standalone relative to libstdc++ and libc++ (TBB 2018 is the critical dependency).

**Comment by brycelelbach** [comment]
Still can't comment on PSTL plans. But I'm going to go ahead and close this one, as I think the cpp backend has this functionality, although it probably needs some love.
