### ISSUE TITLE
THRUST_CUB_NS_POSTFIX redefined when backend is THRUST_DEVICE_SYSTEM_OMP

### ISSUE THREAD

**Issue by hwinkler** [thrust/thrust#965]
This is an update of https://developer.nvidia.com/nvidia_bug/2065814
It is still happening as of commit `3af276e` Wed Mar 20.

Simply including `thrust/device_vector` in a program compiled with `-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_OMP` causes compile warnings to spew to output.

Compiling this program:

```c++
#include <thrust/device_vector.h>

__host__
thrust::device_vector<float> test() {
  thrust::device_vector<float> v;
  return v;
}
```

emits many similar messages to 

```
In file included from /home/hughw/nvidia-bug/omp-build/thrust/thrust/system/cuda/detail/execution_policy.h:33,
                 from /home/hughw/nvidia-bug/omp-build/thrust/thrust/system/cuda/detail/util.h:33,
                 from /home/hughw/nvidia-bug/omp-build/thrust/thrust/system/cuda/detail/terminate.h:31,
                 from /home/hughw/nvidia-bug/omp-build/thrust/thrust/detail/allocator/temporary_allocator.inl:24,
                 from /home/hughw/nvidia-bug/omp-build/thrust/thrust/detail/allocator/temporary_allocator.h:84,
                 from /home/hughw/nvidia-bug/omp-build/thrust/thrust/detail/temporary_array.h:40,
                 from /home/hughw/nvidia-bug/omp-build/thrust/thrust/detail/overlapped_copy.h:23,
                 from /home/hughw/nvidia-bug/omp-build/thrust/thrust/detail/vector_base.inl:24,
                 from /home/hughw/nvidia-bug/omp-build/thrust/thrust/detail/vector_base.h:586,
                 from /home/hughw/nvidia-bug/omp-build/thrust/thrust/device_vector.h:25,
                 from test.cu:1:
/home/hughw/nvidia-bug/omp-build/thrust/thrust/system/cuda/config.h:73: warning: "THRUST_CUB_NS_PREFIX" redefined
 #define THRUST_CUB_NS_PREFIX namespace thrust {   namespace cuda_cub {
```

Please see attached repro code.

[repro.tar.gz](https://github.com/thrust/thrust/files/3004126/repro.tar.gz)

**Comment by hwinkler** [comment]
Some of the messages are about redefining THRUST_CUB_NS_POSTFIX, others about THRUST_CUB_NS_PREFIX.

**Comment by griwes** [comment]
Ah! I see what is going on. `detail/allocator/temporary_allocator.inl` is guarding the include of the CUDA backed with the wrong thing (i.e., it's always including it under NVCC, even though compiling with NVCC doesn't necessarily mean that we're compiling for the CUDA backend). I couldn't repro at first, but then I realized that I wasn't actually using NVCC for compiling for non-CUDA backends.

I know what the fix is, so expect it to land on `master` some time soon.

On another note though, because this is lighting a red light bulb in my brain: why are you compiling Thrust for the OpenMP backend with `nvcc` and not the host compiler? More specifically, because this is the aspect that matters: are you, by any chance, doing that because some other parts of your application use Thrust with the CUDA backend?

**Comment by hwinkler** [comment]
> are you, by any chance, doing that because some other parts of your application use Thrust with the CUDA backend?

I'm glad you asked that! We are just about to undertake doing that because we've just developed a use case. Which is why I was revisiting this issue from a year ago. But this case did not arise from that motivation -- it was simply that our Makefile stopped working well for OMP last year, conveniently about the time we dropped OMP builds.

Our new use case is that our calculation accumulates a set of vectors that continually grow in length. They grow and sometimes need to be appended to one another based on results of the calculation, but they don't participate in the calculation at all. The calculation computes offsets and indexes and such by which we have to join the vectors. There's a list of these vectors that we have to permute and filter.  The vectors hog lots of memory, so if we can move them off the device and manipulate this single list using Thrust + OMP, it could free up lots of scarce device memory.

So now I'm eager to hear your interest in the topic!

**Comment by griwes** [comment]
So, the reason for my interest in this topic is probably not going to make you happy :D The reason why I had an alarm go off in my head is that linking together object files that contain Thrust compiled with different values for `THRUST_{HOST,DEVICE}_SYSTEM` is not supported. Some of the types and other symbols defined in Thrust headers have different definitions, depending on which system you use as the backend system for either host or the device; the obvious cases are `thrust::host_vector`, `thrust::device_vector`, `thrust::device_ptr`, `thrust::device`, but it's hard to quickly list them all comprehensively. Linking together such files immediately causes you to get ODR violations all over the place, which means the behavior of your program is no longer defined.

One thing you can try to do is define the _host_ system to be OMP, and the _device_ system to be CUDA: `-DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_OMP -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA`. This will make your `thrust::host_vector` be an OMP-backed vector. This is something that is supposed to work, but we don't quite test it yet; we plan to start doing extensive testing for the non-CUDA systems as both host and device systems now that we are on Github, so if you go this route, please report any issues you find.

I admit that it'd be much nicer to be able to use multiple different systems like what you're trying to do; there's several ways to do that, and some of them will be rather quite easy once we only support C++11, but if we decide to go that way, it'll certainly warrant announcing it is now Thrust 2, because the changes necessary to client code would be quite extensive, and would require rearchitecting some core parts of Thrust.

**Comment by hwinkler** [comment]
I'm hoping you can make this change to permit the simple case of compiling a Thrust program using nvcc but targeting the CPP or OMP backends to work again.

The use cases we discussed above aren't important to me any more. But still, I would like to be able to compile my codebase as in the old days, by simply setting DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CPP and recompiling using `nvcc`. 

I would not trust a PR from me to fix this, as I don't understand all the implications of changing definitions. But I hate to bug you about it.

**Comment by hwinkler** [comment]
@griwes I came back to say thank you for the tip to set `-DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_OMP -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA`. It works like a champ.
