### ISSUE TITLE
polymorphic_allocator doesn't seem to work with device_memory_resource

### ISSUE THREAD

**Issue by zhihaoy** [thrust/thrust#968]
The following doesn't compile
```cpp
    {
      thrust::device_memory_resource memres;
      thrust::mr::polymorphic_adaptor_resource<void *> adaptor(&memres);
      typedef thrust::mr::polymorphic_allocator<double, void *> Alloc;
      Alloc alloc(&adaptor);

      do_stuff_with_vector<thrust::host_vector<double, Alloc>>(alloc);
    }
```
Nor does
```cpp
    {
      thrust::device_memory_resource memres;
      thrust::mr::polymorphic_adaptor_resource<
          thrust::device_memory_resource::pointer>
          adaptor(&memres);
      typedef thrust::mr::polymorphic_allocator<
          double, thrust::device_memory_resource::pointer>
          Alloc;
      Alloc alloc(&adaptor);

      do_stuff_with_vector<thrust::host_vector<double, Alloc>>(alloc);
    }
```

Do they belong to the same design space?

Took a look at
```c++
template<typename Pointer = void *>
class polymorphic_adaptor_resource THRUST_FINAL : public memory_resource<Pointer>
{
public:
    polymorphic_adaptor_resource(memory_resource<Pointer> * t) : upstream_resource(t)
    {
    }

    virtual void * do_allocate(std::size_t bytes, std::size_t alignment) THRUST_OVERRIDE
    {
        return upstream_resource->allocate(bytes, alignment);
    }
```
Inheriting from `memory_resource<Pointer>` doesn't look right, because `void* do_allocate` can fail to override `Pointer do_allocate` from the base
```
thrust/mr/polymorphic_adaptor.h(34): error: return type is not identical to nor covariant with return type "thrust::cuda_cub::pointer<void>" of overridden virtual function "thrust::mr::memory_resource<Pointer>::do_allocate [with Pointer=thrust::cuda_cub::pointer<void>]"
```
Let's say it's `memory_resource<void*>`, then `void* do_allocate` expects `Pointer` to be convertible to `void*` -- not the case for tagged pointers, so `thrust::device_memory_resource` doesn't work.
```
thrust/mr/polymorphic_adaptor.h(41): error: no suitable constructor exists to convert from "void *" to "thrust::cuda_cub::pointer<void>"
          detected during instantiation of "void thrust::mr::polymorphic_adaptor_resource<Pointer>::do_deallocate(void *, size_t, size_t) [with Pointer=thrust::cuda_cub::pointer<void>]"
```

I'm not familiar with the design, so correct me if I'm wrong.  I merely want a pmr vector that can decide to use device memory or managed memory at runtime.

PS: in the changelog it says `thrust::mr::polymorphic_allocator<T>`, but actually it is `thrust::mr::polymorphic_allocator<T, Pointer>`, and I couldn't make it work with `std::vector` in MSVC
```
std::vector<double, thrust::mr::polymorphic_allocator<double, void*>> v;

2017\Community\VC\Tools\MSVC\14.16.27023\include\xutility(323): error: no instance of constructor "thrust::mr::allocator<T, MR>::allocator [with T=double, MR=thrust::mr::polymorphic_adaptor_resource<void *>]" matches the argument list
          detected during:
            instantiation of "std::_Compressed_pair<_Ty1, _Ty2, false>::_Compressed_pair(std::_Zero_then_variadic_args_t, _Other2 &&...) [with _Ty1=std::_Rebind_alloc_t<thrust::mr::polymorphic_allocator<double, void *>, double>, _Ty2=std::_Vector_val<std::conditional_t<true, std::_Simple_types<double>, std::_Vec_iter_types<double, size_t, ptrdiff_t, double *, const double *, double &, const double &>>>, _Other2=<>]"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vector(422): here
            instantiation of "std::_Vector_alloc<_Alloc_types>::_Vector_alloc() [with _Alloc_types=std::_Vec_base_types<double, thrust::mr::polymorphic_allocator<double, void *>>]"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vector(651): here
            instantiation of "std::vector<_Ty, _Alloc>::vector() [with _Ty=double, _Alloc=thrust::mr::polymorphic_allocator<double, void *>]"
mr_basic.cu(54): here
```

**Comment by griwes** [comment]
D'oh! That is indeed wrong. You've correctly identified the issue.

The polymorphic adapter has been included more as a proof of concept, to show that you can still achieve the `std::pmr` polymorphic semantics even in a design that expects to not make virtual calls (at least at the top level). the `void*`s in its definition should have, in fact, been `Pointer`s.

I'll try to get a fix out to `master` soon, and it should land in the CUDA toolkit the next time we do a proper release.

Re your PS: if that is the line of code you're trying to compile, then it won't, because the polymorphic adapter isn't default constructible.

Btw., glad to see that someone is experimenting with the new toys :)

**Comment by lichray** [comment]
I see.  `std::pmr::polymorphic_allocator` is default constructible though... but I could have read the error message more carefully :) Thanks for working on this.

**Comment by griwes** [comment]
The standard equivalent always knows what global resource to construct itself from, since there's just one. Since the Thrust version of this interface is more statically typed, it's harder to do that sensibly. The default-constructible allocator type that Thrust provides is called `stateless_resource_allocator`, which in a hindsight is a rather bad name and we'll probably want to rename it one day.

The original issue you've reported should be fixed on master now; I don't yet know what release of the CUDA Toolkit the fix will ship in.
