### ISSUE TITLE
Parallel performance on CPU

### ISSUE THREAD

**Issue by agribov2016** [thrust/thrust#999]
thrust::sort is not executed in parallel on CPU. Tried running with flags thrust::system::cpp::par and thrust::host.
Attached sample to compare GPU, CPU using Thrust, and CPU parallel implementations.
[CUDA_sort.zip](https://github.com/thrust/thrust/files/3278145/CUDA_sort.zip)

**Comment by brycelelbach** [comment]
We chatted about this by telecon today; the issue here is that the default Thrust "host" system is a sequential backend. To use one of the parallel host systems, you need to set a pound define:

```
#define THRUST_HOST_SYSTEM THRUST_HOST_SYSTEM_OMP
```

Or set it on the command line.

There are three options for host systems: `OMP` (which requires OpenMP), `TBB` (which requires the TBB library), and `CPP` (which always executes sequentially).
